### ISSUE TITLE
Provide the option to activate either the block or the inject 

### ISSUE THREAD

**Issue by skounis** [skounis/mt-countdown#34]
We should adjust our code and do not Inject the HTML markup in the body of the front page always. 

We should add a checkbox in the Configuration settings of the module. When this option is enabled we should proceed with the injection:

![2018-01-17_18-49-09](https://user-images.githubusercontent.com/690575/35055682-6f229bd0-fbb8-11e7-80c3-8ba64243caa3.png)

**Comment by skounis** [comment]
@a4dyakonov 

When I check out the branch, these changes are pushed, the background color of the area becomes black. Please see 

- https://www.screencast.com/t/3HoCbAZ8a

That's not the behavior we have in the master branch 

- https://www.screencast.com/t/4TgYq7RxrS

It seems that after the changes the "Theme" selection for the option is not taken into account and the Custom colors are used

- https://www.screencast.com/t/YpQzxta0Ky

Could you please check why is that happening?

**Comment by skounis** [comment]
@a4dyakonov It seems that the predefined colors are not working as well

- https://www.screencast.com/t/Y8ydFfYd38L

**Comment by a4dyakonov** [comment]
@skounis I've fixed some color settings in the mt_countdown.settings.yml file.
Unfortunately, the Drupal field "color" doesn't work with RGBA color format that why Drupal  converts the 'rgba(0,0,0,0.6)' value to the '#000000'
All changes were added to the PR.
