### ISSUE TITLE
predefined_palettes variable in block--mt_countdown.html.twig

### ISSUE THREAD

**Issue by skechagia** [skounis/mt-countdown#38]
@skounis In mt_countdown_inject.html.twig file there is {{ predefined_palettes }} variable

https://screencast.com/t/w347cUoPij7O

How we can use the same variable in block--mt_countdown.html.twig, it seems that it is not available in data[] array

https://screencast.com/t/7LljhwhqTw4F

also it is not used in block--mt_countdown.html.twig

https://screencast.com/t/ZTFvFwwy

**Comment by skounis** [comment]
@a4dyakonov 

Could you please check this issue. `{{ predefined_palettes }}` should be used in the default twig file for the block as well.

**Comment by skounis** [comment]
@skechagia I merged the changes made in https://github.com/skounis/mt-countdown/pull/39 into `master` 

Could you please check and confirm?

**Comment by skechagia** [comment]
@skounis I confirm that it's OK now.
